language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
  - /^v\d+(\.\d+)*$/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
script:
- git clone https://github.com/klokantech/gl-style-package-spec.git
- cd gl-style-package-spec
- bash ./task/run.sh
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: build/${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
